modLoader = "javafml"
loaderVersion = "[35.1.0,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "playeranimator"
version = "${version}"
displayName = "Player Animator"
authors = "KosmX"
description = '''
Look for FabricMC (or QuiltMC) builds...
'''
#logoFile = ""

[[dependencies.playeranimator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
