
name: Publish

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'release type'
        required: false
        type: choice
        options:
          - alpha
          - beta
          - release
      changelog:
        description: 'changelog'
        required: false
        default: ''
      upload:
        required: true
        type: choice
        options:
          - true
          - false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check for valid input
        run: |
          if ! ( [ "${{github.event.inputs.type}}" = "alpha" ] || [ "${{github.event.inputs.type}}" = "beta" ] || [ "${{github.event.inputs.type}}" = "release" ] )
          then
          return -1
          fi
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      # Runs a single command using the runners shell
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Publish package
        run: ./gradlew publish --no-daemon
        env:
          KOSMX_MAVEN_USER: ${{ secrets.MAVEN_USER }}
          KOSMX_MAVEN_TOKEN: ${{ secrets.MAVEN_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          CHANGELOG: ${{github.event.inputs.changelog}}
          RELEASE_TYPE: ${{github.event.inputs.type}}
          UPLOAD_TO_PORTAL: ${{github.event.inputs.upload}}
